### ISSUE TITLE
Include quotes

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#10]
I think it'll be great if we can display a motivational quote at each new tab. We can start start by adding a `quotes.txt` file which would contain about 50 quotes. This is because I think we should keep DarkSite an offline extension.  Once we have the file ready, we can randomly read a quote from it and display it on the page. It should be ensured that a new quote is read every time the user opens a new tab.

To claim this issue, please mention the source from where you will be using the quotes.

**Comment by vinaysrivastava273** [comment]
Hi @sudo-rgorai , I am willing to work on this issue. Please assign it to me. 
I will use this source : https://instagramcircus.com/positive-quotes-captions-phrases/

**Comment by sudo-rgorai** [comment]
Hey @vinaysrivastava273. Go ahead. The quotes look good.
