### ISSUE TITLE
Use offline font

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#11]
The page currently uses [this](https://fonts.google.com/specimen/Fredericka+the+Great) font from google fonts. The idea is to use the same font in an offline environment. Would love suggestions on how to implement it.

**Comment by baidi-mannan** [comment]
U can assign this to me...
But the user would have to install that for accessing it.

**Comment by sudo-rgorai** [comment]
Hey @baidi-mannan. Thanks for having a look at this issue. 

> But the user would have to install that for accessing it.

I think chrome caches fonts by default. I'm not sure if asking users to install a font is a good idea. I was thinking something along the lines of including a ttf file as an asset which would be packaged within the extension itself. However I'm not sure how to actually implement it. I shall look for it. Meanwhile if you wish, you can search for it as well and post here if you find something.

**Comment by Nishant2907** [comment]
Hi, I know how to use google fonts offline, i.e. we don't need any internet to load the google fonts in out website. Kindly assign this issue to me 👍

**Comment by sudo-rgorai** [comment]
@Nishant2907 sure. Can you briefly explain what you're planning to do?

**Comment by Nishant2907** [comment]
@sudo-rgorai  we can use @font-face here. What we can do is that every google font has a different font-face of its own and we can simply include it in our css  file to use the google font offline.

**Comment by Nishant2907** [comment]
I have done this work in my forked repo. So should i make  PR or we can also have a discussion on how i did it. :)

**Comment by sudo-rgorai** [comment]
Sure. `@font-face` seems like the way to go ahead. I have suggested some modifications. Please have a look.
