### ISSUE TITLE
Clear console logs from the js files

### ISSUE THREAD

**Issue by Godzilla5111** [sudo-rgorai/DarkSite#17]
Currently, there are a lot of console logs in the script files, which may be necessary for debugging purpose, but need not be shown to the users! I think we can clear them out from the script files in order to avoid unnecessary things being logged into the user's console, and hence, enhance the user's experience.

**Comment by sudo-rgorai** [comment]
Yes. A great issue. Thanks for pointing it out. While you're at it, please see if there's any unused commented code that needs to be cleaned as well. Thanks.

**Comment by Godzilla5111** [comment]
Sure!  I will cleanup the code and send a PR👍
