### ISSUE TITLE
Unusual response from the website

### ISSUE THREAD

**Issue by Nishant2907** [sudo-rgorai/DarkSite#18]
Whenever I run the website locally, there is an unusual response that we can see in the gif below.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/59792198/101280911-ef844080-37f1-11eb-93f9-bc0c1f6da40c.gif)

This was happening with previous commits also.

**Comment by Godzilla5111** [comment]
Have you turned on the extension @Nishant2907? Go to chrome://extensions and turn on the extension. Then it works fine.  Go through the instructions in the readme once. If it still persists, contact @sudo-rgorai .

**Comment by Nishant2907** [comment]
Thanks @Godzilla5111, now its working. Previously the extension was turning off automatically as i closed the browser tab.
