### ISSUE TITLE
Add code of conduct file

### ISSUE THREAD

**Issue by tejan-singh** [sudo-rgorai/DarkSite#19]
- Code of conduct file is missing in the project. I would like to add one.

**Comment by sudo-rgorai** [comment]
Sure. That's a great idea. Can you please briefly mention the contents of what you're planning to write?

**Comment by tejan-singh** [comment]
There is a template which has all the necessary information required for an open source project. I can make a pull request with that and you can check if its good

**Comment by sudo-rgorai** [comment]
@tejan-singh Yes. Let's do that :+1:
