### ISSUE TITLE
Use ES6

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#23]
The current javascript syntax is not completely ES6 compliant. I think it'll a good idea to include several ES6 features in it. Some of them include:

1. Replacing `var` with `let`
2. Using `const` for constants
3. Using [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) instead of regular concatenation.
etc.

**Comment by anushkasinghal11** [comment]
Hey!
I am interested to work on this issue. Please assign it to me.

**Comment by sudo-rgorai** [comment]
@anushkasinghal11 Assigned! :smile:
