### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by tejan-singh** [sudo-rgorai/DarkSite#27]
- Repository is missing necessary contributing.MD file which contains all instructions to follow for contributions.

**Comment by sudo-rgorai** [comment]
Sure. Please add it. I think you can create a `docs` folder and add `Contributing.md` and `CODE_OF_CONDUCT.md` in it. Thanks :smile:

**Comment by tejan-singh** [comment]
both files are actually placed on the main repository without any folder so that GitHub automatically detects them and suggest users to read them while making pull request and open issues. 

You can see below the comment sections at the end of this page, a message is shown "Remember, contributions to this repository should follow its code of conduct. " 

Github automatically referenced the file.
