### ISSUE TITLE
Use CSS grid for shortcuts

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#3]
Currently, the shortcut icons are placed side by side without any particular layout. A grid layout should be used in its place.

**Comment by harshitkathuria** [comment]
I would like to work on this issue

**Comment by sudo-rgorai** [comment]
@harshitkathuria Sure. Go ahead.

**Comment by harshitkathuria** [comment]
@sudo-rgorai , Should I make the grid responsive or should it always contain 4 columns?

**Comment by sudo-rgorai** [comment]
@harshitkathuria Yes even though there's no direct way to use chrome extensions on smaller screens such as mobile phones. But using a responsive layout would be better in my opinion. Thanks :)

**Comment by harshitkathuria** [comment]
@sudo-rgorai Sorry I just tried to make grid responsive at my end, but it doesn't look good as it just pile up the shortcuts like a stack. But if you want it, then I can make it responsive also.

**Comment by harshitkathuria** [comment]
I have created a PR. Please check if that looks good. Thanks :)

**Comment by sudo-rgorai** [comment]
That's alright. What you can do is use an absolute width for `.icons` and for `.links` you can use something like 
`grid-template-columns: repeat(auto-fill, 250px);` 
I think that should fix it. If you want you can give it a try and send another commit to your branch.

**Comment by harshitkathuria** [comment]
Sure, I have done the same and sent another commit to my branch. Please check if it looks good to you. Thanks
