### ISSUE TITLE
Add an issue and a PR template

### ISSUE THREAD

**Issue by Nishant2907** [sudo-rgorai/DarkSite#33]
As I have seen many times people throughout Github sometimes forget about describing the issue or adding any relevant data about it. So that's why there is a need to add an issue and a PR template in this repository

**Comment by sudo-rgorai** [comment]
Yes. This seems like a good idea. I think you can add this to `./CONTRIBUTING.md`.

**Comment by sudo-rgorai** [comment]
Are you intending to work on this @Nishant2907?

**Comment by Nishant2907** [comment]
Yes surely, will do it today itself.

**Comment by sudo-rgorai** [comment]
Hey @Nishant2907. It's been a while. Are you still working on this?

**Comment by sudo-rgorai** [comment]
Removing assignee due to inactivity. This issue is now open for others to claim.
@Nishant2907 feel free to re-claim this issue by commenting here.

**Comment by Aarushi11H** [comment]
Hey! I'd like to take it up. Do I need to add the Issue and PR templates in `.github` folder or `./CONTRIBUTING.md` ?

**Comment by KerinPithawala** [comment]
Can I work on this issue?

**Comment by sudo-rgorai** [comment]
@Aarushi11H @KerinPithawala My apologies to both of you! It seems I missed your comments. If either of you still wants to work on this issue you're welcome to do so. Please comment again if you're still interested, and I shall assign this issue.

**Comment by sudo-rgorai** [comment]
> Do I need to add the Issue and PR templates in `.github` folder or `./CONTRIBUTING.md` ?

Using `.github` folder seems like a better approach. Let's do that. We can also place `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` inside it.

**Comment by KerinPithawala** [comment]
I am interested to work on this issue

**Comment by sudo-rgorai** [comment]
Assigning @KerinPithawala. :blush:

**Comment by sudo-rgorai** [comment]
@Aarushi11H there are several `good first issues` which need attention. You may go through them if you're still looking to contribute. Thanks :relaxed:
