### ISSUE TITLE
Use a different logo.

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#4]
The current logo for the extension has been taken from https://www.flaticon.com/free-icon/sun_740879. An original logo needs to be designed specifically for the extension.

**Comment by prakarsh7695** [comment]
@sudo-rgorai Can you brief what kind of logo do you require?

**Comment by sudo-rgorai** [comment]
Yes. I think the current logo is nice but I'm not sure if we're allowed to use it without the creator's permission. So I was hoping that we can get our own logo.

1. The logo can be somewhat similar to the current one. Or it can be different as well. The only thing is it should look decent. For example, the current logo is pictorial in nature. We can also use one that uses alphabets (DS).
2. It'll be great if we use a logo that follows [material design](http://materialdesignblog.com/15-awesome-material-design-logo-examples-for-your-inspiration/).
3. Since the extension focuses on dark theme, I think the logo should also have dark colors.

**Comment by roli25** [comment]
can I work on this?

**Comment by sudo-rgorai** [comment]
Sure! Please make sure that before sending a PR you share the logo that you have created in this thread for review purpose. :smile:

**Comment by sudo-rgorai** [comment]
Hey @roli25, are you still working on this? Would like an update.

**Comment by sudo-rgorai** [comment]
Removing assignee due to inactivity. This issue is now open for others to claim.
@roli25 feel free to re-claim this issue by commenting here.

**Comment by cigar-galaxy82** [comment]
Hey @sudo-rgorai I would like to work on this issue
