### ISSUE TITLE
Fix date/time alignment

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#40]
Currently, date and time on top bar is skewed to the right. This is due to the addition of a new settings panel. The alignment needs to be centered.

**Comment by Harshith2255** [comment]
Hi
I would like to contribute to this

**Comment by Harshith2255** [comment]
If you have liked the work on the search issue
then I would be happy to proceed with this.

**Comment by sudo-rgorai** [comment]
@Harshith2255 Love your enthusiasm :smile: Let's get #42 completely fixed. And once you're done with that you can work on this. Meanwhile this issue is open and others can claim it.

**Comment by cigar-galaxy82** [comment]
Hey @sudo-rgorai I would like to work on this

**Comment by Harshith2255** [comment]
hey @sudo-rgorai just now completed #42 so is this available

**Comment by sudo-rgorai** [comment]
Assigning @Harshith2255 because #48 is currently assigned to @cigar-galaxy82.
