### ISSUE TITLE
Improve search bar design

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#42]
Currently, the search bar design looks a little off. It can be modified to mimic the original google search bar (with rounded corners and appropriately positioned search icon). A transparent fill (i.e. background) for the search bar can also be used if it looks good.

**Comment by Harshith2255** [comment]
Hi
I would like to contribute to this

**Comment by Harshith2255** [comment]
I have done some work

**Comment by sudo-rgorai** [comment]
My apologies for late correspondence. I have added some feedback to your PR. It'll be great if you try to implement them. Thanks for looking into this issue. I shall assign this to you.

**Comment by Harshith2255** [comment]
Hello @sudo-rgorai 
I wanted to let you know that a PR has been made check it out and clarify any changes required by today itself as there are going to be evaluations on our performance

**Comment by sudo-rgorai** [comment]
Thanks for the PR @Harshith2255. I have merged it! :relaxed:

**Comment by Harshith2255** [comment]
Thanks for the opportunity@sudo-rgorai
