### ISSUE TITLE
Improve settings panel design

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#43]
Currently, the settings panel has been designed to provide just basic functionalities and does not look great. The design needs to be improved. Some features that can be added are:

1. Dark background with light text. Perhaps light borders if required to distinguish from the background.
2. Rounded corners. This is pretty important.
3. Transparency. Should look nice. Not sure though.

These are just general guidelines. It is not required to absolutely follow all of them. But in my opinion they should enhance the look of the settings panel. Similarly, other features not mentioned in this list can also be added.

**Comment by tirlochanarora16** [comment]
@sudo-rgorai, how can I preview this existing design, and if someone else is not working on this can I take up this issue?

**Comment by sudo-rgorai** [comment]
> can I take up this issue?

@tirlochanarora16 Sure! There are no current assignees so you can take up the issue.

> how can I preview this existing design

Just hover above the settings icon on the top-left corner and you should be able to see a drop-down menu. This is what I was referring to when I said `settings panel`. We can let that remain a drop-down OR we can use a modal instead. I personally feel using a modal is a better idea. But I leave the implementation to you.

Thanks for taking up the issue :relaxed:

**Comment by tirlochanarora16** [comment]
@sudo-rgorai, can you please tell me what additional features would you like to see in the settings panel?

**Comment by sudo-rgorai** [comment]
For this issue, there need not be any additional (functional) feature in the settings panel. You are only required to change its look. Currently it is pretty basic. The idea is to improve it's design and make it look decent. The exact details and suggestions on how to that has been provided in the description of this issue.
