### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by tejan-singh** [sudo-rgorai/DarkSite#45]
- Styling readme to make it look attractive
- Adding badges and live stats
- Writing proper description

**Comment by sudo-rgorai** [comment]
@tejan-singh Valid points. Thanks for mentioning them. Are you planning to work on this?

**Comment by tejan-singh** [comment]
Yes! I would like to work on it. We will be gradually Updating and improving documentation in no. of pull requests.

**Comment by tejan-singh** [comment]
should I work on this?? You haven't assigned me this issue
