### ISSUE TITLE
Create a settings panel

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#5]
The content and layout of the page is static. There should be a settings panel where the user can:

1. Change fonts
2. Change username
3. Edit background/shortcut color
4. Change clock type (12 hrs/24 hrs)

**Comment by vinaysrivastava273** [comment]
@sudo-rgorai  I can do this. Please assign it to me.
Also, I am doubtful about how do you want the shortcuts to be customized? Please clarify.

**Comment by sudo-rgorai** [comment]
On second thoughts, I think we should not use settings panel for customizing shortcuts. It would probably be more convenient to do that by right clicking the icons themselves. I shall add a new issue for that and edit this issue for the same.

For fonts, we are going to include two offline fonts i.e, `Fredericka the Great` [1](https://fonts.google.com/specimen/Fredericka+the+Great) and `Montserrat` [2](https://fonts.google.com/specimen/Montserrat). You can read the conversations in #11 #14 and #20 to get more details about this. For rest of the fonts, we can use google fonts. Try using their API to get a list of of all the available fonts and display it to the user. This may be a little tricky and if you face any problem, feel free to comment here and I shall help you with this.

Rest everything should be okay. But do not hesitate to ask for help.
Thanks for taking up this issue.

**Comment by vinaysrivastava273** [comment]
Hey @sudo-rgorai , I read the conversations in the mentioned issues but I'm confused how to use the API to get a list of available fonts. Through [this](https://developers.google.com/fonts/docs/developer_api) website, I have generated an API key and that gives me a very large JSON code. How to proceed now?? Should I create a JSON file and link the file to index.html ? Will that serve the purpose?

**Comment by sudo-rgorai** [comment]
The JSON that you have received contains data about several fonts. One of those fields is `family` which is basically the font name. Run a loop through this JSON data and extract these family names and display these to the user in a drop-down menu. When the user clicks on one of these names, store it in a variable, say `fontFamily`.

Now if you notice, the link statement for using google font has a common syntax. [See here](https://fonts.google.com/specimen/Roboto?sidebar.open=true&selection.family=Roboto). So once you have the `fontFamily` variable, all you need to do is inject the following lines via your JavaScript:

`<link rel="preconnect" href="https://fonts.gstatic.com">`
`<link href="https://fonts.googleapis.com/css2?family=`**`fontFamily`**`&display=swap" rel="stylesheet"> `

Once you have done that, you will need to change the greeting's `font-family`(css) property to `fontFamily`. In this way the greeting's font can be changed.

Whenever you're using JavaScript, make a different `.js` file and work on it. Then import those functions in `index.js`. This is because we are trying to improve code modularity (#9) .

Give this a try. If you need any more help feel free to ask here. If you get _really_ stuck, try to complete as many features as you can and then let me know when you're done. I shall complete the rest.
