### ISSUE TITLE
need to turn off suggestion window

### ISSUE THREAD

**Issue by astroidworld** [sudo-rgorai/DarkSite#50]
It is needed to turn off the suggestion window.it is looking very bad when we are going to type something on the user page.

![issue](https://user-images.githubusercontent.com/75432008/102697355-372bb300-425b-11eb-8554-8c7cea04fbe8.PNG)

**Comment by astroidworld** [comment]
please can you assign this work to me??

**Comment by sudo-rgorai** [comment]
Yes. We should do that.
