### ISSUE TITLE
Use separate stylesheets for each page

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#7]
Currently both pages use the same stylesheet. This may lead to some conflicts later. There should be a directory called `stylesheets` which would contain two different css files and the html files should refer to these files for styling.

**Comment by Godzilla5111** [comment]
@sudo-rgorai please assign it to me!

**Comment by baidi-mannan** [comment]
@sudo-rgorai  please assign this to me

**Comment by sudo-rgorai** [comment]
Assigning @baidi-mannan because #8 has already been assigned to @Godzilla5111

**Comment by baidi-mannan** [comment]
@sudo-rgorai  Thanks!!

**Comment by baidi-mannan** [comment]
Hi! I have solved this issue and created a pull request. please have a look :)
