### ISSUE TITLE
Use dynamic greetings

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#8]
Currently, the greeting is set to _Hi \<User\>!_. A custom greeting should be used depending on the time of the day i.e. _Good Morning_, _Good Afternoon_, _Good Evening_ and _Good Night_.

**Comment by Godzilla5111** [comment]
@sudo-rgorai please allot this to me.

**Comment by sudo-rgorai** [comment]
@Godzilla5111 Assigned :smiley:

**Comment by Godzilla5111** [comment]
Thanks @sudo-rgorai 😊
