### ISSUE TITLE
Improve code modularity

### ISSUE THREAD

**Issue by sudo-rgorai** [sudo-rgorai/DarkSite#9]
Currently, there's a large `index.js` file with several functions within it. Ideally there should be an `src` folder which contains an `index.js` file which imports several other js files. `index.js` should not contain any programming logic but only call functions from other js files. So basically, the whole file needs to be split into various files to improve modularity and allow easy debugging.

**Comment by Nishant2907** [comment]
Hi, kindly assign this issue to me. I can improve the modularity of the code.

**Comment by sudo-rgorai** [comment]
Hey @Nishant2907. Love your enthusiasm. However, since you have already claimed #11 you should work on that first. If you find that difficult or if nobody claims this issue by the time you complete that one, you can work on this as well. Thanks for the help :smile:

**Comment by Nishant2907** [comment]
Hi @sudo-rgorai i have submitted a PR for the issue #11, kindly review it :)

**Comment by Nishant2907** [comment]
Hi @sudo-rgorai as I have finished the previous issue assigned to me, so can i do this one now?

**Comment by sudo-rgorai** [comment]
@Nishant2907 Assigned!
